/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lab200;

/**
 *
 * @author 166348
 */
public class PhysicsForm extends javax.swing.JPanel
{

  /** Creates new form PhysicsForm */
  public PhysicsForm()
  {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    velocityField = new javax.swing.JTextField();
    angleField = new javax.swing.JTextField();
    timeLabel = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    solveProblem = new javax.swing.JButton();
    jLabel8 = new javax.swing.JLabel();
    distanceLabel = new javax.swing.JLabel();
    heightLabel = new javax.swing.JLabel();

    jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
    jLabel1.setText("Initial velocity:");

    jLabel2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
    jLabel2.setText("Angle of elevation:");

    jLabel3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
    jLabel3.setText("Maximum Height:");

    jLabel4.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
    jLabel4.setText("Horizontal Distance:");

    jLabel5.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
    jLabel5.setText("Travel time:");

    velocityField.setText("0");
    velocityField.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        velocityFieldActionPerformed(evt);
      }
    });

    angleField.setText("0");
    angleField.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        angleFieldActionPerformed(evt);
      }
    });

    timeLabel.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
    timeLabel.setText("0.00 sec");

    jLabel7.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
    jLabel7.setText("feet/sec");

    solveProblem.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
    solveProblem.setText("Solve Problem");
    solveProblem.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        solveProblemActionPerformed(evt);
      }
    });

    jLabel8.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
    jLabel8.setText("degrees");

    distanceLabel.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
    distanceLabel.setText("0.00 feet");

    heightLabel.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
    heightLabel.setText("0.00 feet");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel1)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
              .addGap(10, 10, 10)
              .addComponent(jLabel2))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel3)
              .addComponent(jLabel4)
              .addComponent(jLabel5))))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(angleField, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
          .addComponent(velocityField))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel7)
              .addComponent(jLabel8))
            .addGap(43, 43, 43)
            .addComponent(solveProblem))
          .addComponent(distanceLabel)
          .addComponent(heightLabel)
          .addComponent(timeLabel))
        .addContainerGap(42, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel1)
              .addComponent(velocityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel7))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel2)
              .addComponent(angleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel8))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel5)
              .addComponent(timeLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel3)
              .addComponent(heightLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel4)
              .addComponent(distanceLabel)))
          .addComponent(solveProblem))
        .addContainerGap(243, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void velocityFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_velocityFieldActionPerformed
  {//GEN-HEADEREND:event_velocityFieldActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_velocityFieldActionPerformed

  private void angleFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_angleFieldActionPerformed
  {//GEN-HEADEREND:event_angleFieldActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_angleFieldActionPerformed

  private void solveProblemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_solveProblemActionPerformed
  {//GEN-HEADEREND:event_solveProblemActionPerformed
    // TODO add your handling code here:
    double vel = Double.parseDouble(velocityField.getText());
    double ang = Math.toRadians(Double.parseDouble(angleField.getText()));
    
    double grav = 32;
    double time = (2*vel*Math.sin(ang))/grav;
    double height = (Math.pow(vel*Math.sin(ang),2))/(2*grav);
    double distance = (Math.pow(vel,2)*Math.sin(2*ang))/grav;
    
    System.out.println("Time: "+ time);
    System.out.println("Height: "+ height);
    System.out.println("Distance: "+ distance);
    
    timeLabel.setText(String.format("%10.2f", time) + " sec");
    heightLabel.setText(String.format("%10.2f", height) + " feet");
    distanceLabel.setText(String.format("%10.2f", distance) + " feet");
  }//GEN-LAST:event_solveProblemActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JTextField angleField;
  public javax.swing.JLabel distanceLabel;
  public javax.swing.JLabel heightLabel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  public javax.swing.JButton solveProblem;
  public javax.swing.JLabel timeLabel;
  public javax.swing.JTextField velocityField;
  // End of variables declaration//GEN-END:variables
}
