/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lab202;

/**
 *
 * @author 166348
 */
public class StringForm extends javax.swing.JPanel
{

  /** Creates new form StringForm */
  public StringForm()
  {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jComboBox1 = new javax.swing.JComboBox();
    fLab = new javax.swing.JLabel();
    fBox = new javax.swing.JTextField();
    rLab = new javax.swing.JLabel();
    rBox = new javax.swing.JTextField();
    rBut = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    jScrollPane2 = new javax.swing.JScrollPane();
    jTextArea2 = new javax.swing.JTextArea();

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Select One---", "Convert to Uppercase", "Convert to Lowercase", "Length of Input", "Replace" }));
    jComboBox1.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jComboBox1ActionPerformed(evt);
      }
    });

    fLab.setText("Find:");
    fLab.setVisible(false);

    fBox.setVisible(false);

    rLab.setText("Replace:");
    rLab.setVisible(false);

    rBox.setVisible(false);

    rBut.setText("Replace Now");
    rBut.setVisible(false);
    rBut.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        rButActionPerformed(evt);
      }
    });

    jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("Input Text"));

    jTextArea1.setColumns(20);
    jTextArea1.setRows(5);
    jScrollPane1.setViewportView(jTextArea1);

    jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("Output Text"));

    jTextArea2.setEditable(false);
    jTextArea2.setColumns(20);
    jTextArea2.setRows(5);
    jScrollPane2.setViewportView(jTextArea2);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jScrollPane2)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(fLab)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(fBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(rLab)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(rBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(rBut)))
        .addContainerGap(22, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(fLab)
          .addComponent(fBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(rLab)
          .addComponent(rBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(rBut))
        .addGap(18, 18, 18)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBox1ActionPerformed
  {//GEN-HEADEREND:event_jComboBox1ActionPerformed
    // TODO add your handling code here:
    if (jComboBox1.getSelectedIndex() == 3){
      String temp = jTextArea1.getText();
      int len = temp.length();
      jTextArea2.setText("Number of characters: "+len);
    }
    if (jComboBox1.getSelectedIndex() == 2){
      jTextArea2.setText(jTextArea1.getText().toLowerCase());
    }
    if (jComboBox1.getSelectedIndex() == 1){
      jTextArea2.setText(jTextArea1.getText().toUpperCase());
    }
    if (jComboBox1.getSelectedIndex() != 4){
      fBox.setVisible(false);
      fLab.setVisible(false);
      rLab.setVisible(false);
      rBox.setVisible(false);
      rBut.setVisible(false);
    }
    else {
      fBox.setVisible(true);
      fLab.setVisible(true);
      rLab.setVisible(true);
      rBox.setVisible(true);
      rBut.setVisible(true);
    }
  }//GEN-LAST:event_jComboBox1ActionPerformed

  private void rButActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rButActionPerformed
  {//GEN-HEADEREND:event_rButActionPerformed
    // TODO add your handling code here:
    String temp = jTextArea1.getText();
    jTextArea2.setText(temp.replace(fBox.getText(), rBox.getText()));
  }//GEN-LAST:event_rButActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField fBox;
  private javax.swing.JLabel fLab;
  private javax.swing.JComboBox jComboBox1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTextArea jTextArea1;
  private javax.swing.JTextArea jTextArea2;
  private javax.swing.JTextField rBox;
  private javax.swing.JButton rBut;
  private javax.swing.JLabel rLab;
  // End of variables declaration//GEN-END:variables
}
