/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lab600;

/**
 *
 * @author 166348
 */
public class NumberForm extends javax.swing.JPanel
{

  /** Creates new form NumberForm */
  public NumberForm()
  {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jLabel2 = new javax.swing.JLabel();
    numField = new javax.swing.JTextField();
    calculate = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    factorsText = new javax.swing.JTextArea();
    jLabel3 = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    primesText = new javax.swing.JTextArea();

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
    jLabel2.setText("Enter a whole number:");

    numField.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

    calculate.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
    calculate.setText("Calculate");
    calculate.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        calculateActionPerformed(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
    jLabel1.setText("Factors");

    factorsText.setEditable(false);
    factorsText.setColumns(20);
    factorsText.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
    factorsText.setLineWrap(true);
    factorsText.setRows(5);
    factorsText.setWrapStyleWord(true);
    jScrollPane1.setViewportView(factorsText);

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
    jLabel3.setText("Primes");

    primesText.setEditable(false);
    primesText.setColumns(20);
    primesText.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
    primesText.setLineWrap(true);
    primesText.setRows(5);
    primesText.setWrapStyleWord(true);
    jScrollPane2.setViewportView(primesText);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel2)
            .addGap(18, 18, 18)
            .addComponent(numField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(calculate))
          .addGroup(layout.createSequentialGroup()
            .addGap(21, 21, 21)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel3)
                  .addComponent(jLabel1))
                .addGap(0, 0, Short.MAX_VALUE))
              .addComponent(jScrollPane2))))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jLabel2)
            .addComponent(numField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(calculate))
        .addGap(18, 18, 18)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void calculateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_calculateActionPerformed
  {//GEN-HEADEREND:event_calculateActionPerformed
    // TODO add your handling code here:
    factorsText.setText(getFactors(numField.getText()));
    primesText.setText(getPrimes(numField.getText()));
  }//GEN-LAST:event_calculateActionPerformed

  public String getFactors(String input){
    String text = "";
    if(!input.isEmpty()){
      int num = (int) Double.parseDouble(input);
      if(num>1){
        for(int i = 1; i <= num; i++){
          if(num%i == 0){
            text = text+i+" ";
          }
        }
      }
    }
    return text;
  }
  
  boolean isPrime(long n) {
    if(n < 2) return false;
    if(n == 2 || n == 3) return true;
    if(n%2 == 0 || n%3 == 0) return false;
    long sqrtN = (long)Math.sqrt(n)+1;
    for(long i = 6L; i <= sqrtN; i += 6) {
        if(n%(i-1) == 0 || n%(i+1) == 0) return false;
    }
    return true;
}
  
  public String getPrimes(String input){
    String text = "";
    if(!input.isEmpty()){
      int num = (int) Double.parseDouble(input);
      if(num>1){
        text = text+"2 ";
        for(int i = 3; i <= num; i+=2){
          if(isPrime(i)){
            text = text+i+" ";
          }
          printProgress(num,i);
        }
      }
    }
    printProgress(100,100);
    return text;
  }
  
  public void printProgress(int max, int cur){
	    numPercent = (int) ((((double)(cur))/max)*100);
	    numPercent = (int) ((((double)(numPercent))/100)*length);
		String output = "[";
		for(int i = 0; i < numPercent; i++){
			output = output+".";
		}
		for(int i = 0; i < (length-numPercent); i++){
			output = output+" ";
		}
		output = output+"]"+(int)((((double)(numPercent))/(double)(length))*100)+"%\n";
		System.out.print(output);
	}
  
  int numPercent = 0;
  int length = 40;
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton calculate;
  private javax.swing.JTextArea factorsText;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTextField numField;
  private javax.swing.JTextArea primesText;
  // End of variables declaration//GEN-END:variables
}
