/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lab501;

/**
 *
 * @author 166348
 */
public class SortForm extends javax.swing.JPanel
{

  /** Creates new form SortForm */
  public SortForm()
  {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    sorted = new javax.swing.JLabel();
    num1 = new javax.swing.JTextField();
    num2 = new javax.swing.JTextField();
    num3 = new javax.swing.JTextField();
    sort = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();

    sorted.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    sorted.setText("Sorted: ");

    num1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    num1.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        num1ActionPerformed(evt);
      }
    });

    num2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    num2.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        num2ActionPerformed(evt);
      }
    });

    num3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    num3.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        num3ActionPerformed(evt);
      }
    });

    sort.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    sort.setText("Sort");
    sort.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        sortActionPerformed(evt);
      }
    });

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    jLabel2.setText("Enter 3 Values:");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(sort))
          .addComponent(sorted))
        .addContainerGap(13, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(sort))
          .addComponent(jLabel2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(sorted)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void num1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_num1ActionPerformed
  {//GEN-HEADEREND:event_num1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_num1ActionPerformed

  private void num2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_num2ActionPerformed
  {//GEN-HEADEREND:event_num2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_num2ActionPerformed

  private void num3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_num3ActionPerformed
  {//GEN-HEADEREND:event_num3ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_num3ActionPerformed

  private void sortActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sortActionPerformed
  {//GEN-HEADEREND:event_sortActionPerformed
    // TODO add your handling code here:
    if (numSort)
    sortNums();
    else
    sortLetters();
  }//GEN-LAST:event_sortActionPerformed

  public void sortNums(){
    inputI[0]=Integer.parseInt(num1.getText());
    inputI[1]=Integer.parseInt(num2.getText());
    inputI[2]=Integer.parseInt(num3.getText());
    for(int i = 0; i<inputI.length; i++){
      for(int ii = 0; ii<inputI.length-1; ii++){
        if (inputI[ii]>inputI[ii+1]){
          int tempI = inputI[ii];
          inputI[ii]=inputI[ii+1];
          inputI[ii+1] = tempI;
        }
      }
    }
    sorted.setText("Sorted: "+inputI[0]+", "+inputI[1]+", "+inputI[2]);
  }
  
  public void sortLetters(){
    inputS[0]=num1.getText().toLowerCase();
    inputS[1]=num2.getText().toLowerCase();
    inputS[2]=num3.getText().toLowerCase();
    for(int i = 0; i<inputS.length; i++){
      for(int ii = 0; ii<inputS.length-1; ii++){
        if (inputS[ii].compareTo(inputS[ii+1])>0){
          String tempS = inputS[ii];
          inputS[ii] = inputS[ii+1];
          inputS[ii+1] = tempS;
        }
      }
    }
    sorted.setText("Sorted: "+inputS[0]+", "+inputS[1]+", "+inputS[2]);
  }
  
  String[] inputS = {"","",""};
  int[] inputI = {0,0,0};
  
  boolean numSort = true;
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel2;
  private javax.swing.JTextField num1;
  private javax.swing.JTextField num2;
  private javax.swing.JTextField num3;
  private javax.swing.JButton sort;
  private javax.swing.JLabel sorted;
  // End of variables declaration//GEN-END:variables
}
