/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lab502;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;

/**
 *
 * @author 
 */
public class SegmentForm extends javax.swing.JPanel
{
  
    
  /** Creates new form SegmentForm */
  public SegmentForm()
  {
    initComponents();
  }
  
  @Override
  public void paintComponent(Graphics g)
  {
    super.paintComponent(g);
    g.drawLine(200, 300, 800, 300);
    g.drawLine(500, 0, 500, 600);
    g.setFont(new Font("Consolas", Font.BOLD, 24));
    g.drawString("10", 505, 20);
    g.drawString("10", 775, 320);
    
    if (pressed){
      calculateNums(g);
      g.drawLine((int) xPoints[0],(int) yPoints[0],(int) xPoints[1],(int) yPoints[1]);
      g.fillOval((int) xPoints[0]-4,(int) yPoints[0]-4,8,8);
      g.fillOval((int) xPoints[1]-4,(int) yPoints[1]-4,8,8);
    }
    
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jtfX1 = new javax.swing.JTextField();
    jtfX2 = new javax.swing.JTextField();
    jtfY1 = new javax.swing.JTextField();
    jtfY2 = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    calculate = new javax.swing.JButton();
    jLabel10 = new javax.swing.JLabel();
    mpLabel = new javax.swing.JLabel();
    slopeLabel = new javax.swing.JLabel();
    perpBisLabel = new javax.swing.JLabel();

    setBackground(new java.awt.Color(225, 225, 225));

    jtfX1.setText("-2");
    jtfX1.addFocusListener(new java.awt.event.FocusAdapter()
    {
      public void focusGained(java.awt.event.FocusEvent evt)
      {
        jtfX1FocusGained(evt);
      }
    });

    jtfX2.setText("4");
    jtfX2.addFocusListener(new java.awt.event.FocusAdapter()
    {
      public void focusGained(java.awt.event.FocusEvent evt)
      {
        jtfX2FocusGained(evt);
      }
    });

    jtfY1.setText("5");
    jtfY1.addFocusListener(new java.awt.event.FocusAdapter()
    {
      public void focusGained(java.awt.event.FocusEvent evt)
      {
        jtfY1FocusGained(evt);
      }
    });

    jtfY2.setText("3");
    jtfY2.addFocusListener(new java.awt.event.FocusAdapter()
    {
      public void focusGained(java.awt.event.FocusEvent evt)
      {
        jtfY2FocusGained(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
    jLabel1.setText("A(");

    jLabel2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
    jLabel2.setText("B(");

    jLabel3.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
    jLabel3.setText(",");

    jLabel4.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
    jLabel4.setText(",");

    jLabel5.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
    jLabel5.setText(")");

    jLabel6.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
    jLabel6.setText(")");

    jLabel7.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
    jLabel7.setText("Slope AB:");

    jLabel8.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
    jLabel8.setText("Midpoint AB:");

    jLabel9.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
    jLabel9.setText("Perp. Bis.");

    calculate.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
    calculate.setText("Calculate");
    calculate.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        calculateActionPerformed(evt);
      }
    });

    jLabel10.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N

    mpLabel.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
    mpLabel.setText("( , )");

    slopeLabel.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
    slopeLabel.setText("???");

    perpBisLabel.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
    perpBisLabel.setText("???");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                      .addComponent(jLabel1)
                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                      .addComponent(jtfX1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                      .addComponent(jLabel2)
                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                      .addComponent(jtfX2)))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                      .addComponent(jtfY1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                      .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                      .addComponent(jtfY2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                      .addComponent(jLabel6))))
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(calculate, javax.swing.GroupLayout.Alignment.LEADING))
              .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 620, Short.MAX_VALUE))
          .addComponent(mpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(slopeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(perpBisLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(jtfX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3)
          .addComponent(jtfY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel5))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(jLabel4)
          .addComponent(jtfX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jtfY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel6))
        .addGap(33, 33, 33)
        .addComponent(calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(30, 30, 30)
        .addComponent(jLabel8)
        .addGap(18, 18, 18)
        .addComponent(mpLabel)
        .addGap(72, 72, 72)
        .addComponent(jLabel10)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel7)
        .addGap(18, 18, 18)
        .addComponent(slopeLabel)
        .addGap(48, 48, 48)
        .addComponent(jLabel9)
        .addGap(18, 18, 18)
        .addComponent(perpBisLabel)
        .addContainerGap(68, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void calculateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_calculateActionPerformed
  {//GEN-HEADEREND:event_calculateActionPerformed
    // TODO add your handling code here:
    pressed = true;
    super.repaint();
  }//GEN-LAST:event_calculateActionPerformed

  private void jtfX1FocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jtfX1FocusGained
  {//GEN-HEADEREND:event_jtfX1FocusGained
    // TODO add your handling code here:
    jtfX1.selectAll();
  }//GEN-LAST:event_jtfX1FocusGained

  private void jtfY1FocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jtfY1FocusGained
  {//GEN-HEADEREND:event_jtfY1FocusGained
    // TODO add your handling code here:
    jtfY1.selectAll();
  }//GEN-LAST:event_jtfY1FocusGained

  private void jtfX2FocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jtfX2FocusGained
  {//GEN-HEADEREND:event_jtfX2FocusGained
    // TODO add your handling code here:
    jtfX2.selectAll();
  }//GEN-LAST:event_jtfX2FocusGained

  private void jtfY2FocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jtfY2FocusGained
  {//GEN-HEADEREND:event_jtfY2FocusGained
    // TODO add your handling code here:
    jtfY2.selectAll();
  }//GEN-LAST:event_jtfY2FocusGained

  public void calculateNums(Graphics g){
    xPoints[0] = Double.parseDouble(jtfX1.getText());
    tempX[0] = xPoints[0];
    xPoints[0] = xPoints[0]*((double)300/10)+500;
    xPoints[1] = Double.parseDouble(jtfX2.getText());
    tempX[1] = xPoints[1];
    xPoints[1] = xPoints[1]*((double)300/10)+500;
    yPoints[0] = Double.parseDouble(jtfY1.getText());
    tempY[0] = yPoints[0];
    yPoints[0] = (300)-yPoints[0]*((double)300/10);
    yPoints[1] = Double.parseDouble(jtfY2.getText());
    tempY[1] = yPoints[1];
    yPoints[1] = (300)-yPoints[1]*((double)300/10);
    
    double midX = (tempX[0]+tempX[1])/((double)(2));
    double midY = (tempY[0]+tempY[1])/((double)(2));
    
    String midText = String.format("(%1.1f, %1.1f)", midX, midY);
    
    mpLabel.setText(midText);
    
    String slopeS = "";
    String perpSlopeS = "";
    double perpSlope = 0.0;
    double perpB = 0.0;
    
    g.setColor(Color.BLUE);
    
    if (tempX[0] != tempX[1]){//slope != undef
      double slope = (tempY[0]-tempY[1])/(tempX[0]-tempX[1]);
      slopeS = ""+slope;
      if (tempY[0] != tempY[1]){//slope != 0
        perpSlope = -(1/slope);
        perpB = (midY)-(midX*perpSlope);
        if (perpB>0){
          perpSlopeS = "y = "+(perpSlope)+"x+"+(perpB);
        }
        else if (perpB == 0){
          perpSlopeS = "y = "+perpSlope+"x";
        }
        else {
          perpSlopeS = (perpSlope)+"x"+(perpB);
        }
        double perpY1 = perpSlope*(-10)+perpB;
        double perpY2 = perpSlope*(10)+perpB;
        g.drawLine((int) (10*((double)300/10)+500), (int) ((300)-perpY2*((double)300/10)), (int) ((-10)*((double)300/10)+500), (int) ((300)-perpY1*((double)300/10)));
      }
      else {//slope = 0
        slopeS = "0.0";
        perpSlopeS = "x = "+midX;
        g.drawLine((int) (midX*((double)300/10)+500), 0, (int) (midX*((double)300/10)+500), 600);
      }
    }
    else {//slope = undef
      if (tempY[0] != tempY[1]){
        slopeS = "Undefined";
        perpSlopeS = "y = "+midY;
        g.drawLine(200, (int) ((300)-midY*((double)300/10)), 800, (int) ((300)-midY*((double)300/10)));
      }
      else {
        slopeS = "No Slope";
        perpSlopeS = "Does Not Exist";
        mpLabel.setText("No Midpoint");
      }
    }
    
    slopeLabel.setText(slopeS);
    perpBisLabel.setText(perpSlopeS);
    
    g.setColor(Color.BLACK);
  }
  
  
  double[] xPoints = {0,0};
  double[] yPoints = {0,0};
  double[] tempX = {0,0};
  double[] tempY = {0,0};
  private boolean pressed = false;
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton calculate;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JTextField jtfX1;
  private javax.swing.JTextField jtfX2;
  private javax.swing.JTextField jtfY1;
  private javax.swing.JTextField jtfY2;
  private javax.swing.JLabel mpLabel;
  private javax.swing.JLabel perpBisLabel;
  private javax.swing.JLabel slopeLabel;
  // End of variables declaration//GEN-END:variables
}
