/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lab601;

import java.util.Scanner;

/**
 *
 * @author 166348
 */
public class Stats extends javax.swing.JPanel
{

  /** Creates new form Stats */
  public Stats()
  {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jLabel1 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    outputArea = new javax.swing.JTextArea();
    jScrollPane2 = new javax.swing.JScrollPane();
    inputArea = new javax.swing.JTextArea();
    calcBut = new javax.swing.JButton();

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel1.setText("Enter values seperated by space/tab/enter");

    outputArea.setEditable(false);
    outputArea.setColumns(20);
    outputArea.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
    outputArea.setLineWrap(true);
    outputArea.setRows(5);
    outputArea.setWrapStyleWord(true);
    jScrollPane1.setViewportView(outputArea);

    inputArea.setColumns(20);
    inputArea.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
    inputArea.setLineWrap(true);
    inputArea.setRows(5);
    inputArea.setWrapStyleWord(true);
    jScrollPane2.setViewportView(inputArea);

    calcBut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    calcBut.setText("Calculate Statistics...");
    calcBut.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        calcButActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(calcBut))
        .addGap(14, 14, 14))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(calcBut))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1)
          .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE))
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void calcButActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_calcButActionPerformed
  {//GEN-HEADEREND:event_calcButActionPerformed
    // TODO add your handling code here:
    String inText = inputArea.getText();
    Scanner input = new Scanner(inText);
    int n = 1;
    double sum = 0;
    double mean = 0;
    
    double numSqrdSum = 0;
    double min = input.nextDouble();
    double max = min;
    sum+=min;
    numSqrdSum+=Math.pow(min,2);
    while(input.hasNext()){
      n++;
      double inInt = input.nextDouble();
      sum+=inInt;
      numSqrdSum+=Math.pow(inInt,2);
      if(inInt<min)
        min = inInt;
      if(inInt>max)
        max = inInt;
    }
    mean = sum/n;
    double sumSqrd = Math.pow(sum,2);
    double standDev = Math.sqrt(((double)(1)/(n-1))*(numSqrdSum-(((1)/((double)(n)))*sumSqrd)));
    String outputString = "          n = "+n+"\n        sum = "+sum+"\n       mean = "+mean+"\n          σ = "+standDev+"\n    minimum = "+min+"\n    maximum = "+max;
    outputArea.setText(outputString);
  }//GEN-LAST:event_calcButActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton calcBut;
  private javax.swing.JTextArea inputArea;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTextArea outputArea;
  // End of variables declaration//GEN-END:variables
}
