/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lab700;

import java.util.ArrayList;
import java.util.Scanner;

/**
 *
 * @author 166348
 */
public class ExprForm extends javax.swing.JPanel
{

  ArrayList<String> in = new ArrayList<String>();
  
  /** Creates new form ExprForm */
  public ExprForm()
  {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jLabel1 = new javax.swing.JLabel();
    inputField = new javax.swing.JTextField();
    evalButton = new javax.swing.JButton();
    ansLabel = new javax.swing.JLabel();

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
    jLabel1.setText("Enter a valid postfix expression. Seperate operators and operands with spaces.");

    inputField.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N

    evalButton.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
    evalButton.setText("Evaluate");
    evalButton.setMargin(new java.awt.Insets(2, 28, 2, 28));
    evalButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        evalButtonActionPerformed(evt);
      }
    });

    ansLabel.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
    ansLabel.setText("Answer:");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1)
          .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(evalButton)
            .addGap(18, 18, 18)
            .addComponent(ansLabel)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(evalButton)
          .addComponent(ansLabel))
        .addContainerGap(32, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  public void editArray(int i, double endVal){
    in.remove(i);
    in.remove(i-1);
    in.set(i-2, ""+endVal);
  }
  
  private void evalButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_evalButtonActionPerformed
  {//GEN-HEADEREND:event_evalButtonActionPerformed
    // TODO add your handling code here:
    Scanner sc = new Scanner(inputField.getText());
    while(sc.hasNext()){
      in.add(sc.next());
      System.out.println(in.get(in.size()-1));
    }
    int i = 0;
    double fnum = 0;
    double snum = 0;
    while(in.size() > 1){
      i = 0;
      fnum = 0;
      snum = 0;
      while(true){
        if(in.get(i).equals("+")){
          double endVal = fnum+snum;
          editArray(i, endVal);
          break;
        }
        else if(in.get(i).equals("-")){
          double endVal = fnum-snum;
          editArray(i, endVal);
          break;
        }
        else if(in.get(i).equals("*")){
          double endVal = fnum*snum;
          editArray(i, endVal);
          break;
        }
        else if(in.get(i).equals("/")){
          double endVal = fnum/snum;
          editArray(i, endVal);
          break;
        }
        else if(in.get(i).equals("^")){
          double endVal = Math.pow(fnum,snum);
          editArray(i, endVal);
          break;
        }
        fnum = snum;
        snum = Double.parseDouble(in.get(i));
        i++;
      }
    }
    ansLabel.setText("Answer: "+in.get(0));
  }//GEN-LAST:event_evalButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel ansLabel;
  private javax.swing.JButton evalButton;
  private javax.swing.JTextField inputField;
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
}
