/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lab402;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author David Rogers
 */
public class TriangleForm extends javax.swing.JPanel
{

  /** Creates new form TriangleForm */
  public TriangleForm()
  {
    initComponents();
  }

  @Override
  public void paintComponent(Graphics g)
  {
    super.paintComponent(g);
    g.setFont(new java.awt.Font("Consolas", java.awt.Font.BOLD, 16));

    g.setColor(Color.BLACK);
    g.drawLine(530, 10, 530, 510);
    g.drawLine(280, 260, 780, 260);
    g.drawString(""+slider.getValue(), 770, 275);
    g.drawString(""+slider.getValue(), 535, 20);
    
    if (pressed)
      drawTri(g);
  }


  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        x1_text = new javax.swing.JTextField();
        y1_text = new javax.swing.JTextField();
        x2_text = new javax.swing.JTextField();
        y2_text = new javax.swing.JTextField();
        x3_text = new javax.swing.JTextField();
        y3_text = new javax.swing.JTextField();
        goButton = new javax.swing.JButton();
        slider = new javax.swing.JSlider();
        labelAB = new javax.swing.JLabel();
        labelBC = new javax.swing.JLabel();
        labelAC = new javax.swing.JLabel();
        labelA = new javax.swing.JLabel();
        labelB = new javax.swing.JLabel();
        labelC = new javax.swing.JLabel();
        labelArea = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jLabel1.setText(" B: x2 =");

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jLabel2.setText(" A: x1 =");

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jLabel3.setText(" C: x3 =");

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jLabel4.setText("y1 =");

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jLabel5.setText("y2 =");

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jLabel6.setText("y3 =");

        x1_text.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        x1_text.setText("150");
        x1_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                x1_textFocusGained(evt);
            }
        });

        y1_text.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        y1_text.setText("50");
        y1_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                y1_textFocusGained(evt);
            }
        });

        x2_text.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        x2_text.setText("-200");
        x2_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                x2_textFocusGained(evt);
            }
        });

        y2_text.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        y2_text.setText("100");
        y2_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                y2_textFocusGained(evt);
            }
        });

        x3_text.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        x3_text.setText("0");
        x3_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                x3_textFocusGained(evt);
            }
        });

        y3_text.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        y3_text.setText("-175");
        y3_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                y3_textFocusGained(evt);
            }
        });

        goButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        goButton.setText("Calculate!");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        slider.setMajorTickSpacing(50);
        slider.setMaximum(250);
        slider.setMinimum(10);
        slider.setMinorTickSpacing(25);
        slider.setPaintLabels(true);
        slider.setPaintTicks(true);
        slider.setValue(250);
        slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });
        slider.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                sliderCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        labelAB.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        labelAB.setText("   AB =");

        labelBC.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        labelBC.setText("   BC =");

        labelAC.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        labelAC.setText("   AC =");

        labelA.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        labelA.setText("  m<A = °");

        labelB.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        labelB.setText("  m<B = °");

        labelC.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        labelC.setText("  m<C = °");

        labelArea.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        labelArea.setText(" Area = ");

        jLabel7.setText("Zoom");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labelC, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelArea, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelA, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelB, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelAC, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelAB, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelBC, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(x3_text, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(x1_text, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(x2_text, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(y2_text, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(y1_text, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(y3_text, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(553, 553, 553))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x1_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y1_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x2_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y2_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x3_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y3_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelAB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelBC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelArea, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(goButton)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        x1_text.selectAll();
    }// </editor-fold>//GEN-END:initComponents

  private void goButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_goButtonActionPerformed
  {//GEN-HEADEREND:event_goButtonActionPerformed
    // TODO add your handling code here:
    super.repaint();
    pressed = true;
  }//GEN-LAST:event_goButtonActionPerformed

  private void sliderCaretPositionChanged(java.awt.event.InputMethodEvent evt)//GEN-FIRST:event_sliderCaretPositionChanged
  {//GEN-HEADEREND:event_sliderCaretPositionChanged
    // TODO add your handling code here:
    super.repaint();
  }//GEN-LAST:event_sliderCaretPositionChanged

  private void sliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_sliderStateChanged
  {//GEN-HEADEREND:event_sliderStateChanged
    // TODO add your handling code here:
    super.repaint();
  }//GEN-LAST:event_sliderStateChanged

  private void x1_textFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_x1_textFocusGained
  {//GEN-HEADEREND:event_x1_textFocusGained
    // TODO add your handling code here:
    x1_text.selectAll();
  }//GEN-LAST:event_x1_textFocusGained

  private void y1_textFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_y1_textFocusGained
  {//GEN-HEADEREND:event_y1_textFocusGained
    // TODO add your handling code here:
    y1_text.selectAll();
  }//GEN-LAST:event_y1_textFocusGained

  private void x2_textFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_x2_textFocusGained
  {//GEN-HEADEREND:event_x2_textFocusGained
    // TODO add your handling code here:
    x2_text.selectAll();
  }//GEN-LAST:event_x2_textFocusGained

  private void y2_textFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_y2_textFocusGained
  {//GEN-HEADEREND:event_y2_textFocusGained
    // TODO add your handling code here:
    y2_text.selectAll();
  }//GEN-LAST:event_y2_textFocusGained

  private void x3_textFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_x3_textFocusGained
  {//GEN-HEADEREND:event_x3_textFocusGained
    // TODO add your handling code here:
    x3_text.selectAll();
  }//GEN-LAST:event_x3_textFocusGained

  private void y3_textFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_y3_textFocusGained
  {//GEN-HEADEREND:event_y3_textFocusGained
    // TODO add your handling code here:
    y3_text.selectAll();
  }//GEN-LAST:event_y3_textFocusGained

  public void drawTri(Graphics g){
    int xPointsMod[] = {Integer.parseInt(x1_text.getText()), Integer.parseInt(x2_text.getText()), Integer.parseInt(x3_text.getText())};
    int yPointsMod[] = {Integer.parseInt(y1_text.getText()), Integer.parseInt(y2_text.getText()), Integer.parseInt(y3_text.getText())};
    int xPointsInit[] = {Integer.parseInt(x1_text.getText()), Integer.parseInt(x2_text.getText()), Integer.parseInt(x3_text.getText())};
    int yPointsInit[] = {Integer.parseInt(y1_text.getText()), Integer.parseInt(y2_text.getText()), Integer.parseInt(y3_text.getText())};
    for(int i = 0; i<3; i++){
      xPointsMod[i] = (int) (xPointsMod[i]*((double)(250)/slider.getValue()));
      xPointsMod[i] += 530;
    }
    for(int i = 0; i<3; i++){
      yPointsMod[i] = (int) (yPointsMod[i]*((double)(250)/slider.getValue()));
      yPointsMod[i] = 260-yPointsMod[i];
    }
    g.drawPolygon(xPointsMod, yPointsMod, xPointsMod.length);
    g.drawString("A("+x1_text.getText()+","+y1_text.getText()+")", xPointsMod[0], yPointsMod[0]);
    g.drawString("B("+x2_text.getText()+","+y2_text.getText()+")", xPointsMod[1], yPointsMod[1]);
    g.drawString("C("+x3_text.getText()+","+y3_text.getText()+")", xPointsMod[2], yPointsMod[2]);
    
    double abDist = Math.sqrt(Math.pow(xPointsInit[0]-xPointsInit[1],2)+Math.pow(yPointsInit[0]-yPointsInit[1],2));
    double acDist = Math.sqrt(Math.pow(xPointsInit[0]-xPointsInit[2],2)+Math.pow(yPointsInit[0]-yPointsInit[2],2));
    double bcDist = Math.sqrt(Math.pow(xPointsInit[2]-xPointsInit[1],2)+Math.pow(yPointsInit[2]-yPointsInit[1],2));
    
    labelAB.setText("   AB = "+String.format("%6.2f", abDist));
    labelAC.setText("   AC = "+String.format("%6.2f", acDist));
    labelBC.setText("   BC = "+String.format("%6.2f", bcDist));
    
    labelA.setText("  m<A = "+String.format("%6.2f", cosines(bcDist,abDist,acDist))+"°");
    labelB.setText("  m<B = "+String.format("%6.2f", cosines(acDist,abDist,bcDist))+"°");
    labelC.setText("  m<C = "+String.format("%6.2f", cosines(abDist,bcDist,acDist))+"°");
    
    labelArea.setText(" Area = "+String.format("%6.2f", heron(abDist,acDist,bcDist)));
  }
  
  public double heron(double a, double b, double c){
    double val = 0.0;
    double s = (a+b+c)/2;
    val = Math.sqrt(s*(s-a)*(s-b)*(s-c));
    return val;
  }
  
  public double cosines(double c, double a, double b){
    double val = 0.0;
    val = Math.acos((Math.pow(c,2)-Math.pow(b,2)-Math.pow(a,2))/(-2*a*b));
    return Math.toDegrees(val);
  }
  
    private boolean pressed = false;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelA;
    private javax.swing.JLabel labelAB;
    private javax.swing.JLabel labelAC;
    private javax.swing.JLabel labelArea;
    private javax.swing.JLabel labelB;
    private javax.swing.JLabel labelBC;
    private javax.swing.JLabel labelC;
    private javax.swing.JSlider slider;
    private javax.swing.JTextField x1_text;
    private javax.swing.JTextField x2_text;
    private javax.swing.JTextField x3_text;
    private javax.swing.JTextField y1_text;
    private javax.swing.JTextField y2_text;
    private javax.swing.JTextField y3_text;
    // End of variables declaration//GEN-END:variables
}
