/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lab102;

import java.awt.Font;
/**
 *
 * @author 166348
 */
public class TextPanel extends javax.swing.JPanel
{

  /** Creates new form TextPanel */
  public TextPanel()
  {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    plainB = new javax.swing.JButton();
    italicsB = new javax.swing.JButton();
    boldB = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();

    plainB.setText("plain");
    plainB.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        plainBActionPerformed(evt);
      }
    });

    italicsB.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
    italicsB.setText("italics");
    italicsB.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        italicsBActionPerformed(evt);
      }
    });

    boldB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    boldB.setText("bold");
    boldB.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        boldBActionPerformed(evt);
      }
    });

    jTextArea1.setColumns(20);
    jTextArea1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
    jTextArea1.setRows(5);
    jScrollPane1.setViewportView(jTextArea1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1)
          .addGroup(layout.createSequentialGroup()
            .addComponent(plainB)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(italicsB)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(boldB)
            .addGap(0, 177, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(plainB)
          .addComponent(italicsB)
          .addComponent(boldB))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void plainBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_plainBActionPerformed
  {//GEN-HEADEREND:event_plainBActionPerformed
    // TODO add your handling code here:
    jTextArea1.setFont(new Font("Consolas", Font.PLAIN, 14));
  }//GEN-LAST:event_plainBActionPerformed

  private void italicsBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_italicsBActionPerformed
  {//GEN-HEADEREND:event_italicsBActionPerformed
    // TODO add your handling code here:
    jTextArea1.setFont(new Font("Consolas", Font.ITALIC, 14));
  }//GEN-LAST:event_italicsBActionPerformed

  private void boldBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_boldBActionPerformed
  {//GEN-HEADEREND:event_boldBActionPerformed
    // TODO add your handling code here:
    jTextArea1.setFont(new Font("Consolas", Font.BOLD, 14));
  }//GEN-LAST:event_boldBActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton boldB;
  private javax.swing.JButton italicsB;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea jTextArea1;
  private javax.swing.JButton plainB;
  // End of variables declaration//GEN-END:variables
}
