/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lab101;

/**
 *
 * @author 166348
 */

import java.awt.Color;

public class ControlPanel extends javax.swing.JPanel
{

  /** Creates new form ControlPanel */
  public ControlPanel()
  {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    blackB = new javax.swing.JButton();
    greenB = new javax.swing.JButton();
    redB = new javax.swing.JButton();
    blueB = new javax.swing.JButton();

    setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

    jTextArea1.setColumns(20);
    jTextArea1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    jTextArea1.setRows(5);
    jScrollPane1.setViewportView(jTextArea1);

    blackB.setText("Black Text");
    blackB.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        blackBActionPerformed(evt);
      }
    });

    greenB.setText("Green Text");
    greenB.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        greenBActionPerformed(evt);
      }
    });

    redB.setText("Red Text");
    redB.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        redBActionPerformed(evt);
      }
    });

    blueB.setText("Blue Text");
    blueB.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        blueBActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(blackB)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(greenB)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(redB)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(blueB)))
        .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(blackB)
          .addComponent(greenB)
          .addComponent(redB)
          .addComponent(blueB))
        .addGap(0, 16, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void blackBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_blackBActionPerformed
  {//GEN-HEADEREND:event_blackBActionPerformed
    // TODO add your handling code here:
    jTextArea1.setForeground(Color.BLACK);
  }//GEN-LAST:event_blackBActionPerformed

  private void greenBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_greenBActionPerformed
  {//GEN-HEADEREND:event_greenBActionPerformed
    // TODO add your handling code here:
    jTextArea1.setForeground(Color.GREEN);
  }//GEN-LAST:event_greenBActionPerformed

  private void redBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_redBActionPerformed
  {//GEN-HEADEREND:event_redBActionPerformed
    // TODO add your handling code here:
    jTextArea1.setForeground(Color.RED);
  }//GEN-LAST:event_redBActionPerformed

  private void blueBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_blueBActionPerformed
  {//GEN-HEADEREND:event_blueBActionPerformed
    // TODO add your handling code here:
    jTextArea1.setForeground(Color.BLUE);
  }//GEN-LAST:event_blueBActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton blackB;
  private javax.swing.JButton blueB;
  private javax.swing.JButton greenB;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea jTextArea1;
  private javax.swing.JButton redB;
  // End of variables declaration//GEN-END:variables
}
