/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lab401;

/**
 *
 * @author 166348
 */
public class CalendarForm extends javax.swing.JPanel
{

  /** Creates new form CalendarForm */
  public CalendarForm()
  {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jLabel1 = new javax.swing.JLabel();
    eYear = new javax.swing.JTextField();
    calculateE = new javax.swing.JButton();
    answerL = new javax.swing.JLabel();

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel1.setText("Enter Year:");

    calculateE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    calculateE.setText("Calculate");
    calculateE.setToolTipText("");
    calculateE.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        calculateEActionPerformed(evt);
      }
    });

    answerL.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    answerL.setText("Easter is Sunday,");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addGap(18, 18, 18)
        .addComponent(eYear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(calculateE)
        .addGap(18, 18, 18)
        .addComponent(answerL, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(calculateE, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
            .addComponent(answerL))
          .addGroup(layout.createSequentialGroup()
            .addComponent(eYear)
            .addGap(2, 2, 2))
          .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
        .addContainerGap(38, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents
  
  private void calculateEActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_calculateEActionPerformed
  {//GEN-HEADEREND:event_calculateEActionPerformed
    // TODO add your handling code here:
    int y = Integer.parseInt(eYear.getText());
    int a = y%19;
    int b = y/100;
    int c = y%100;
    int d = b/4;
    int e = b%4;
    int g = (8*b+13)/25;
    int h = (19*a+b-d-g+15)%30;
    int j = c/4;
    int k = c%4;
    int m = (a+11*h)/319;
    int r = (2*e+2*j-k-h+m+32)%7;
    int n = (h-m+r+90)/25;
    int p = (h-m+r+n+19)%32;
//    System.out.println(a+"\n"+b+"\n"+c+"\n"+d+"\n"+e+"\n"+g+"\n"+h+"\n"+j+"\n"+k+"\n"+m+"\n"+r+"\n"+n+"\n"+p);
      String month = Integer.toString(n);
      month = month.replace("3", "March");
      month = month.replace("4", "April");
//    if (n == 3){
//      month = "March";
//    }
//    else if(n == 4){
//      month = "April";
//    }
    
    answerL.setText("Easter is Sunday, " + month + " " + p);
  }//GEN-LAST:event_calculateEActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel answerL;
  private javax.swing.JButton calculateE;
  private javax.swing.JTextField eYear;
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
}
